[package]
name = "websocket-redis-example"
version = "0.1.0"
edition = "2021"

[dependencies]
redis = { version = "0.27.5", features = ["r2d2", "tokio-comp", "aio"]}
futures-util = "0.3"
actix-web = "4"
actix-ws = "0.3.0"
r2d2 = "0.8"
tokio = { version = "1", features = ["rt", "time", "macros"] }
