services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "PING"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    volumes: 
      - cache:/data

  websocket-redis:
    # image: websocket-redis-example
    build: .
    ports:
     - '8080:8080'
    depends_on:
      redis:
        condition: service_healthy

volumes:
  cache:
